#include <stdlib.h>
#include <string.h>

#include <glib.h>

#include "ACAP.h"
#include "ota_scene.h"
#include "ota_translator.h"

static const char* OTA_JS_COMMON =
"var OTA_VERSION = 1;\n"
"var OTA_MAX_BODY = 47;\n"
"var OTA_COMMANDS = {\n"
"  get: 0x01,\n"
"  set: 0x02,\n"
"  caps: 0x03,\n"
"  list: 0x04,\n"
"  get_response: 0x81,\n"
"  set_ack: 0x82,\n"
"  caps_response: 0x83,\n"
"  list_response: 0x84,\n"
"  error: 0xE0\n"
"};\n"
"var OTA_USE_CASES = { counting: 1, occupancy: 2, presence: 3, presenceAlert: 3 };\n"
"var OTA_CLASSES = ['human', 'car', 'bike', 'bus', 'truck', 'other'];\n"
"\n"
"function byte(value) {\n"
"  return Number(value) & 0xFF;\n"
"}\n"
"\n"
"function commandCode(value) {\n"
"  if (typeof value === 'number') return byte(value);\n"
"  var command = OTA_COMMANDS[String(value || '').replace(/-/g, '_')];\n"
"  if (command == null) throw new Error('Unsupported command ' + value);\n"
"  return command;\n"
"}\n"
"\n"
"function crc8(values) {\n"
"  var crc = 0;\n"
"  for (var index = 0; index < values.length; index++) {\n"
"    crc ^= byte(values[index]);\n"
"    for (var bit = 0; bit < 8; bit++) {\n"
"      crc = (crc & 0x80) ? ((crc << 1) ^ 0x07) & 0xFF : (crc << 1) & 0xFF;\n"
"    }\n"
"  }\n"
"  return crc;\n"
"}\n"
"\n"
"function bytesToHex(values) {\n"
"  return values.map(function (value) {\n"
"    return ('0' + byte(value).toString(16)).slice(-2);\n"
"  }).join('').toUpperCase();\n"
"}\n"
"\n"
"function hexToBytes(value) {\n"
"  if (Array.isArray(value)) return value.map(byte);\n"
"  var text = String(value || '').replace(/\\s+/g, '');\n"
"  if (!text.length || text.length % 2 || !/^[0-9a-f]+$/i.test(text)) {\n"
"    throw new Error('Payload must be even-length HEX');\n"
"  }\n"
"  var result = [];\n"
"  for (var index = 0; index < text.length; index += 2) {\n"
"    result.push(parseInt(text.slice(index, index + 2), 16));\n"
"  }\n"
"  return result;\n"
"}\n"
"\n"
"function appendU16(output, value) {\n"
"  var number = Number(value) & 0xFFFF;\n"
"  output.push(number & 0xFF, (number >> 8) & 0xFF);\n"
"}\n"
"\n"
"function readU16(values, offset) {\n"
"  return byte(values[offset]) | (byte(values[offset + 1]) << 8);\n"
"}\n"
"\n"
"function readU32(values, offset) {\n"
"  return (\n"
"    byte(values[offset]) +\n"
"    byte(values[offset + 1]) * 0x100 +\n"
"    byte(values[offset + 2]) * 0x10000 +\n"
"    byte(values[offset + 3]) * 0x1000000\n"
"  );\n"
"}\n"
"\n"
"function makeFrame(command, transactionId, body) {\n"
"  var frame = [byte(command), OTA_VERSION, byte(transactionId)].concat(body || []);\n"
"  if (frame.length + 1 > 51) throw new Error('OTA frame exceeds 51 bytes');\n"
"  frame.push(crc8(frame));\n"
"  return bytesToHex(frame);\n"
"}\n"
"\n"
"function classMask(value) {\n"
"  if (typeof value === 'number') return value & 0x3F;\n"
"  var mask = 0;\n"
"  if (Array.isArray(value)) {\n"
"    value.forEach(function (name) {\n"
"      var index = OTA_CLASSES.indexOf(name);\n"
"      if (index >= 0) mask |= 1 << index;\n"
"    });\n"
"    return mask;\n"
"  }\n"
"  value = value || {};\n"
"  OTA_CLASSES.forEach(function (name, index) {\n"
"    if (value[name]) mask |= 1 << index;\n"
"  });\n"
"  return mask;\n"
"}\n"
"\n"
"function classObject(mask) {\n"
"  var result = {};\n"
"  OTA_CLASSES.forEach(function (name, index) {\n"
"    result[name] = Boolean(mask & (1 << index));\n"
"  });\n"
"  return result;\n"
"}\n"
"\n"
"function useCaseIndex(value) {\n"
"  if (typeof value === 'number') return value;\n"
"  var index = OTA_USE_CASES[value];\n"
"  if (!index) throw new Error('Unknown use case ' + value);\n"
"  return index;\n"
"}\n"
"\n"
"function sceneFor(port, selector) {\n"
"  var group = OTA_SCENE_MAPS[String(port)];\n"
"  if (!group) throw new Error('No scene map for port ' + port);\n"
"  selector = selector || {};\n"
"  var scene;\n"
"  if (selector.index != null) {\n"
"    scene = group.scenes.filter(function (item) {\n"
"      return item.index === Number(selector.index);\n"
"    })[0];\n"
"  } else if (selector.id != null) {\n"
"    scene = group.scenes.filter(function (item) {\n"
"      return item.id === Number(selector.id);\n"
"    })[0];\n"
"  } else if (selector.name != null) {\n"
"    scene = group.scenes.filter(function (item) {\n"
"      return item.name === selector.name;\n"
"    })[0];\n"
"  }\n"
"  if (!scene) throw new Error('Scene not found');\n"
"  return { group: group, scene: scene };\n"
"}\n"
"\n"
"function sceneSelector(message) {\n"
"  if (message.sceneIndex != null) return { index: message.sceneIndex };\n"
"  if (message.sceneId != null) return { id: message.sceneId };\n"
"  return { name: message.scene != null ? message.scene : message.name };\n"
"}\n"
"\n"
"function integerCoordinate(value) {\n"
"  var number = Number(value);\n"
"  if (!Number.isInteger(number) || number < 0 || number > 1000) {\n"
"    throw new Error('Coordinates must be integers from 0 through 1000');\n"
"  }\n"
"  return number;\n"
"}\n"
"\n"
"function appendIntegerPoint(output, x, y) {\n"
"  var packed = integerCoordinate(x) + integerCoordinate(y) * 0x400;\n"
"  output.push(packed & 0xFF, (packed >> 8) & 0xFF, (packed >> 16) & 0x0F);\n"
"}\n";

static const char* OTA_ENCODER_JS =
"function encodeSceneSet(port, message, transactionId) {\n"
"  var found = sceneFor(port, sceneSelector(message));\n"
"  var config = message.config || message;\n"
"  var points = config.points || config.vertices || [];\n"
"  var minimumPoints = port === 131 ? 2 : 3;\n"
"  if (points.length < minimumPoints || points.length > 10) {\n"
"    throw new Error('Invalid point count');\n"
"  }\n"
"\n"
"  var fields;\n"
"  if (port === 131) {\n"
"    fields = [\n"
"      config.direction === 'rightToLeft' ? 1 : 0,\n"
"      classMask(config.publishClasses),\n"
"      0\n"
"    ];\n"
"  } else if (port === 132) {\n"
"    var valueTypes = { max: 0, min: 1, average: 2, avg: 2 };\n"
"    if (valueTypes[config.valueType] == null) throw new Error('Invalid valueType');\n"
"    fields = [classMask(config.publishClasses), valueTypes[config.valueType], 0];\n"
"  } else {\n"
"    var triggerDelay = Number(config.triggerDelaySeconds);\n"
"    fields = [\n"
"      classMask(config.classes || config.detectionClasses),\n"
"      Number(config.thresholdObjectCount),\n"
"      triggerDelay & 0xFF,\n"
"      (triggerDelay >> 8) & 0xFF\n"
"    ];\n"
"  }\n"
"\n"
"  var pointsPerPage = Math.floor((OTA_MAX_BODY - 13 - fields.length) / 3);\n"
"  var pageCount = Math.ceil(points.length / pointsPerPage);\n"
"  var frames = [];\n"
"  for (var page = 0; page < pageCount; page++) {\n"
"    var pointStart = page * pointsPerPage;\n"
"    var pointCount = Math.min(pointsPerPage, points.length - pointStart);\n"
"    var body = [2, found.scene.index];\n"
"    appendU16(body, found.scene.id);\n"
"    appendU16(body, found.scene.fingerprint);\n"
"    appendU16(body, found.group.mapFingerprint);\n"
"    body.push(page, pageCount, pointStart, pointCount, points.length);\n"
"    body = body.concat(fields);\n"
"\n"
"    for (var index = 0; index < pointCount; index++) {\n"
"      var point = points[pointStart + index];\n"
"      var x = Array.isArray(point) ? point[0] : point.x;\n"
"      var y = Array.isArray(point) ? point[1] : point.y;\n"
"      appendIntegerPoint(body, x, y);\n"
"    }\n"
"    frames.push(makeFrame(OTA_COMMANDS.set, transactionId, body));\n"
"  }\n"
"  return frames;\n"
"}\n"
"\n"
"function normalizeMessage(input) {\n"
"  var message = Object.assign({}, input || {});\n"
"  var config = Object.assign({}, message.config || {});\n"
"  var type = String(message.type || '').replace(/[ _-]/g, '').toLowerCase();\n"
"  var portsByType = {\n"
"    action: 100,\n"
"    control: 100,\n"
"    lora: 110,\n"
"    lorawan: 110,\n"
"    information: 120,\n"
"    info: 120,\n"
"    publish: 130,\n"
"    counting: 131,\n"
"    occupancy: 132,\n"
"    presence: 133,\n"
"    presencealert: 133\n"
"  };\n"
"\n"
"  if (message.port == null && portsByType[type] != null) message.port = portsByType[type];\n"
"  var port = Number(message.port);\n"
"  if (!Number.isInteger(port)) throw new Error('Provide a supported type or numeric port');\n"
"  if ([100, 110, 120, 130, 131, 132, 133].indexOf(port) < 0) {\n"
"    throw new Error('Unsupported OTA port ' + port);\n"
"  }\n"
"\n"
"  if (config.service != null && config.useCase == null) config.useCase = config.service;\n"
"  if (config.active != null && config.enabled == null) config.enabled = config.active;\n"
"  if (config.intervall != null && config.intervalMinutes == null) config.intervalMinutes = config.intervall;\n"
"  if (config.interval != null && config.intervalMinutes == null) config.intervalMinutes = config.interval;\n"
"  if (config.adr != null && config.adrEnabled == null) config.adrEnabled = config.adr;\n"
"  if (message.action == null && config.action != null) message.action = config.action;\n"
"  if (message.infoType == null && config.service != null) message.infoType = config.service;\n"
"  if (message.page == null && config.page != null) message.page = config.page;\n"
"  if (message.scene == null && config.scene != null) message.scene = config.scene;\n"
"  if (message.sceneId == null && config.sceneId != null) message.sceneId = config.sceneId;\n"
"  if (message.sceneIndex == null && config.sceneIndex != null) message.sceneIndex = config.sceneIndex;\n"
"\n"
"  if (message.command == null) {\n"
"    if (port === 100) {\n"
"      message.command = 'set';\n"
"    } else if (port === 110) {\n"
"      message.command = config.dataRate != null || config.adrEnabled != null ? 'set' : 'get';\n"
"    } else if (port === 120) {\n"
"      message.command = 'get';\n"
"    } else if (port === 130) {\n"
"      message.command = config.enabled != null || config.intervalMinutes != null ? 'set' : 'get';\n"
"    } else if (port >= 131 && port <= 133) {\n"
"      var hasGeometry = config.points != null || config.vertices != null;\n"
"      message.command = hasGeometry ? 'set' : 'get';\n"
"    }\n"
"  }\n"
"\n"
"  message.config = config;\n"
"  return message;\n"
"}\n"
"\n"
"function encodedResult(port, frames) {\n"
"  if (frames.length === 1) return { port: port, message: frames[0] };\n"
"  return { port: port, messages: frames };\n"
"}\n"
"\n"
"/**\n"
" * Encode a JSON OTA request for a LoRaWAN downlink.\n"
" * Returns { port: Number, message: String }, or messages for paged geometry.\n"
" */\n"
"function Encode(message) {\n"
"  message = normalizeMessage(message);\n"
"  var port = Number(message.port);\n"
"  var command = commandCode(message.command);\n"
"  var transactionId = byte(message.transactionId || 0);\n"
"  var config = message.config || message;\n"
"  var body = [];\n"
"  var frames;\n"
"\n"
"  if (command === OTA_COMMANDS.caps) {\n"
"    body = [];\n"
"  } else if (command === OTA_COMMANDS.list) {\n"
"    if (port < 131 || port > 133) throw new Error('LIST is unsupported on port ' + port);\n"
"    body = [byte(message.page || 0)];\n"
"  } else if (command === OTA_COMMANDS.get) {\n"
"    if (port === 110) {\n"
"      body = [];\n"
"    } else if (port === 120) {\n"
"      var informationTypes = { camera: 1, cameraInfo: 1, bridge: 2, bridgeInfo: 2 };\n"
"      body = [informationTypes[message.infoType] || Number(message.infoType), byte(message.page || 0)];\n"
"    } else if (port === 130) {\n"
"      body = [useCaseIndex(message.useCase || config.useCase)];\n"
"    } else if (port >= 131 && port <= 133) {\n"
"      var found = sceneFor(port, sceneSelector(message));\n"
"      body = [found.scene.index, byte(message.page || 0)];\n"
"    } else {\n"
"      throw new Error('GET is unsupported on port ' + port);\n"
"    }\n"
"  } else if (command === OTA_COMMANDS.set) {\n"
"    if (port === 100) {\n"
"      var actions = { restartBridge: 1, resetAllData: 2 };\n"
"      body = [actions[message.action] || Number(message.action)];\n"
"    } else if (port === 110) {\n"
"      var fieldMask = 0;\n"
"      if (config.dataRate != null) fieldMask |= 0x01;\n"
"      if (config.adrEnabled != null) fieldMask |= 0x02;\n"
"      body = [fieldMask, byte(config.dataRate || 0), config.adrEnabled ? 1 : 0];\n"
"    } else if (port === 130) {\n"
"      var useCase = useCaseIndex(config.useCase || message.useCase);\n"
"      body = [useCase, config.enabled ? 1 : 0];\n"
"      if (useCase !== OTA_USE_CASES.presence) body.push(byte(config.intervalMinutes));\n"
"    } else if (port >= 131 && port <= 133) {\n"
"      frames = encodeSceneSet(port, message, transactionId);\n"
"    } else {\n"
"      throw new Error('SET is unsupported on port ' + port);\n"
"    }\n"
"  } else {\n"
"    throw new Error('Only GET, SET, CAPS and LIST can be encoded');\n"
"  }\n"
"\n"
"  if (!frames) frames = [makeFrame(command, transactionId, body)];\n"
"  return encodedResult(port, frames);\n"
"}\n"
"\n"
"function EncodeHex(message) {\n"
"  var result = Encode(message);\n"
"  if (!result.message) throw new Error('Message requires multiple frames; use Encode');\n"
"  return result.message;\n"
"}\n"
"\n"
"/*\n"
" * JSON input examples for every OTA port\n"
" *\n"
" * Port 100 - execute an action:\n"
" * { \"type\": \"Action\", \"config\": { \"action\": \"restartBridge\" } }\n"
" *\n"
" * Port 110 - set LoRaWAN configuration:\n"
" * { \"type\": \"LoRaWAN\", \"config\": { \"dataRate\": 3, \"adr\": true } }\n"
" *\n"
" * Port 120 - request information:\n"
" * { \"type\": \"Information\", \"config\": { \"service\": \"camera\", \"page\": 0 } }\n"
" *\n"
" * Port 130 - configure publishing:\n"
" * { \"type\": \"Publish\", \"config\": { \"service\": \"counting\", \"active\": true, \"intervall\": 5 } }\n"
" *\n"
" * Port 131 - configure an existing Counting scene:\n"
" * { \"type\": \"Counting\", \"sceneIndex\": 1, \"config\": { \"direction\": \"leftToRight\", \"publishClasses\": [\"human\"], \"points\": [[250, 500], [750, 500]] } }\n"
" *\n"
" * Port 132 - configure an existing Occupancy scene:\n"
" * { \"type\": \"Occupancy\", \"sceneIndex\": 1, \"config\": { \"publishClasses\": [\"human\", \"car\"], \"valueType\": \"average\", \"points\": [[250, 250], [750, 250], [750, 750], [250, 750]] } }\n"
" *\n"
" * Port 133 - configure an existing Presence Alert scene:\n"
" * { \"type\": \"PresenceAlert\", \"sceneIndex\": 1, \"config\": { \"classes\": [\"human\"], \"thresholdObjectCount\": 1, \"triggerDelaySeconds\": 10, \"points\": [[250, 250], [750, 250], [750, 750], [250, 750]] } }\n"
" *\n"
" * Usage:\n"
" * var output = Encode({\n"
" *   type: 'Publish',\n"
" *   config: { service: 'counting', active: true, intervall: 5 }\n"
" * });\n"
" * // { port: 130, message: '02010001010555' }\n"
" *\n"
" * Geometry can require multiple frames. In that case Encode returns\n"
" * { port: Number, messages: String[] }; send each message in order.\n"
" */\n"
"\n";

static const char* OTA_DECODER_JS =
"function commandName(command) {\n"
"  for (var name in OTA_COMMANDS) {\n"
"    if (OTA_COMMANDS[name] === command) return name;\n"
"  }\n"
"  return 'unknown_' + command;\n"
"}\n"
"\n"
"function statusName(status) {\n"
"  return ({\n"
"    0: 'ok',\n"
"    1: 'invalidLength',\n"
"    2: 'invalidValue',\n"
"    3: 'invalidRange',\n"
"    4: 'crcMismatch',\n"
"    5: 'unknownCommand',\n"
"    6: 'unknownScene',\n"
"    7: 'sceneFingerprintMismatch',\n"
"    8: 'mapFingerprintMismatch',\n"
"    9: 'partialPagePending',\n"
"    10: 'applyFailed',\n"
"    11: 'unsupported'\n"
"  })[status] || 'unknown_' + status;\n"
"}\n"
"\n"
"function parseCapabilities(result, port, body) {\n"
"  if (port === 100) {\n"
"    result.actions = body.map(function (action) {\n"
"      return ({ 1: 'restartBridge', 2: 'resetAllData' })[action] || action;\n"
"    });\n"
"  } else if (port === 110) {\n"
"    if (body.length !== 3) throw new Error('Invalid LoRaWAN capabilities length');\n"
"    result.dataRate = { minimum: body[0], maximum: body[1] };\n"
"    result.adrSupported = Boolean(body[2]);\n"
"  } else if (port === 120) {\n"
"    if (body.length !== 3) throw new Error('Invalid information capabilities length');\n"
"    result.informationTypes = body.slice(0, 2).map(function (type) {\n"
"      return ({ 1: 'cameraInfo', 2: 'bridgeInfo' })[type] || type;\n"
"    });\n"
"    result.legacyTextBytesPerPage = body[2];\n"
"  } else if (port === 130) {\n"
"    if (body.length % 4) throw new Error('Invalid publish capabilities length');\n"
"    result.useCases = [];\n"
"    for (var offset = 0; offset < body.length; offset += 4) {\n"
"      result.useCases.push({\n"
"        useCase: ({ 1: 'counting', 2: 'occupancy', 3: 'presence' })[body[offset]] || body[offset],\n"
"        intervalSupported: Boolean(body[offset + 1]),\n"
"        minimumIntervalMinutes: body[offset + 2],\n"
"        maximumIntervalMinutes: body[offset + 3]\n"
"      });\n"
"    }\n"
"  } else if (port >= 131 && port <= 133) {\n"
"    if (body.length !== 7) throw new Error('Invalid scene capabilities length');\n"
"    result.configVersion = body[0];\n"
"    result.maximumScenes = body[1];\n"
"    result.maximumBodyBytes = body[2];\n"
"    result.pagingSupported = Boolean(body[3]);\n"
"    result.scenesPerListPage = body[4];\n"
"    result.minimumPoints = body[5];\n"
"    result.maximumPoints = body[6];\n"
"  }\n"
"  return result;\n"
"}\n"
"\n"
"function parseInformation(result, complete) {\n"
"  var fields = result.text.split(',');\n"
"  if (result.infoType === 'cameraInfo' && fields.length >= 5) {\n"
"    result.model = fields[0];\n"
"    result.serial = fields[1];\n"
"    result.firmware = fields[2];\n"
"    result.uptimeHours = Number(fields[3].replace(/h$/, ''));\n"
"    var appVersionIndex = 4;\n"
"    if (/%$/.test(fields[4])) {\n"
"      result.cpuUsagePercent = Number(fields[4].replace(/%$/, ''));\n"
"      appVersionIndex = 5;\n"
"    }\n"
"    if (complete) result.appVersion = fields.slice(appVersionIndex).join(',');\n"
"    else result.appVersionFragment = fields.slice(appVersionIndex).join(',');\n"
"  } else if (result.infoType === 'bridgeInfo' && complete && fields.length >= 6) {\n"
"    var identity = fields[0].split('/');\n"
"    result.hardware = identity[0];\n"
"    result.hardwareVersion = identity.slice(1).join('/');\n"
"    result.firmware = fields[1];\n"
"    result.powerSource = fields[2];\n"
"    result.temperatureC = Number(fields[3].replace(/C$/, ''));\n"
"    result.restartCounter = Number(fields[4].replace(/^R/, ''));\n"
"    result.devAddr = fields[5];\n"
"  }\n"
"  return result;\n"
"}\n"
"\n"
"function parseStructuredInformation(result, body) {\n"
"  var fixedLength = result.infoType === 'cameraInfo' ? 10 : 11;\n"
"  if (body.length < fixedLength) throw new Error('Structured information body too short');\n"
"  var fieldLengths = body.slice(2, result.infoType === 'cameraInfo' ? 6 : 7);\n"
"  var expectedLength = fixedLength + fieldLengths.reduce(function (sum, length) {\n"
"    return sum + length;\n"
"  }, 0);\n"
"  if (body.length !== expectedLength) throw new Error('Invalid structured information length');\n"
"  var offset = fixedLength;\n"
"  function readString(length) {\n"
"    var value = String.fromCharCode.apply(null, body.slice(offset, offset + length));\n"
"    offset += length;\n"
"    return value;\n"
"  }\n"
"\n"
"  if (result.infoType === 'cameraInfo') {\n"
"    result.model = readString(fieldLengths[0]);\n"
"    result.serial = readString(fieldLengths[1]);\n"
"    result.firmware = readString(fieldLengths[2]);\n"
"    result.appVersion = readString(fieldLengths[3]);\n"
"    result.uptimeHours = readU32(body, 6);\n"
"  } else if (result.infoType === 'bridgeInfo') {\n"
"    result.hardware = readString(fieldLengths[0]);\n"
"    result.hardwareVersion = readString(fieldLengths[1]);\n"
"    result.firmware = readString(fieldLengths[2]);\n"
"    result.powerSource = readString(fieldLengths[3]);\n"
"    result.devAddr = readString(fieldLengths[4]);\n"
"    var temperatureTenths = readU16(body, 7);\n"
"    if (temperatureTenths & 0x8000) temperatureTenths -= 0x10000;\n"
"    result.temperatureC = temperatureTenths / 10;\n"
"    result.restartCounter = readU16(body, 9);\n"
"  }\n"
"  return result;\n"
"}\n"
"\n"
"function parseFrame(port, input) {\n"
"  var frame = hexToBytes(input);\n"
"  if (frame.length < 4 || frame.length > 51) throw new Error('Invalid OTA frame length');\n"
"  if (crc8(frame.slice(0, -1)) !== frame[frame.length - 1]) throw new Error('CRC mismatch');\n"
"  if (frame[1] !== OTA_VERSION) throw new Error('Unsupported protocol version');\n"
"\n"
"  var command = frame[0];\n"
"  var body = frame.slice(3, -1);\n"
"  var result = {\n"
"    port: Number(port),\n"
"    command: commandName(command),\n"
"    commandCode: command,\n"
"    transactionId: frame[2]\n"
"  };\n"
"  var useCaseNames = { 1: 'counting', 2: 'occupancy', 3: 'presence' };\n"
"  var isScenePort = port === 131 || port === 132 || port === 133;\n"
"\n"
"  if (command === OTA_COMMANDS.error) {\n"
"    if (body.length !== 2) throw new Error('Invalid error response length');\n"
"    result.requestCommand = body[0];\n"
"    result.requestCommandName = commandName(body[0]);\n"
"    result.status = body[1];\n"
"    result.statusName = statusName(body[1]);\n"
"    return result;\n"
"  }\n"
"  if (command === OTA_COMMANDS.set_ack) {\n"
"    var statusOffset = port === 110 ? 0 : 1;\n"
"    if (body.length !== statusOffset + 1) throw new Error('Invalid SET acknowledgement length');\n"
"    result.status = body[statusOffset];\n"
"    result.statusName = statusName(result.status);\n"
"    if (port === 100) result.action = ({ 1: 'restartBridge', 2: 'resetAllData' })[body[0]] || body[0];\n"
"    else if (port === 130) result.useCase = useCaseNames[body[0]] || body[0];\n"
"    else if (isScenePort) result.sceneIndex = body[0];\n"
"    return result;\n"
"  }\n"
"  if (command === OTA_COMMANDS.caps_response) {\n"
"    return parseCapabilities(result, port, body);\n"
"  }\n"
"  if (isScenePort && command === OTA_COMMANDS.list) {\n"
"    result.page = body[0] || 0;\n"
"    return result;\n"
"  }\n"
"  if (isScenePort && command === OTA_COMMANDS.list_response) {\n"
"    if (body.length < 6) throw new Error('Scene list body too short');\n"
"    var entryCount = body[5];\n"
"    if (body.length !== 6 + entryCount * 6) throw new Error('Invalid scene list body length');\n"
"    var sceneGroup = OTA_SCENE_MAPS[String(port)];\n"
"    result.mapFingerprint = readU16(body, 0);\n"
"    result.totalScenes = body[2];\n"
"    result.page = body[3];\n"
"    result.pageCount = body[4];\n"
"    result.scenes = [];\n"
"    for (var sceneOffset = 0; sceneOffset < entryCount; sceneOffset++) {\n"
"      var entryOffset = 6 + sceneOffset * 6;\n"
"      var sceneIndex = body[entryOffset];\n"
"      var mappedScene = sceneGroup && sceneGroup.scenes.filter(function (item) {\n"
"        return item.index === sceneIndex;\n"
"      })[0];\n"
"      var scene = {\n"
"        index: sceneIndex,\n"
"        id: readU16(body, entryOffset + 1),\n"
"        fingerprint: readU16(body, entryOffset + 3),\n"
"        pointCount: body[entryOffset + 5]\n"
"      };\n"
"      if (mappedScene) scene.name = mappedScene.name;\n"
"      result.scenes.push(scene);\n"
"    }\n"
"    return result;\n"
"  }\n"
"  if (isScenePort && command === OTA_COMMANDS.get) {\n"
"    var requested = sceneFor(port, { index: body[0] });\n"
"    result.scene = {\n"
"      index: requested.scene.index,\n"
"      id: requested.scene.id,\n"
"      name: requested.scene.name,\n"
"      fingerprint: requested.scene.fingerprint,\n"
"      mapFingerprint: requested.group.mapFingerprint\n"
"    };\n"
"    result.page = body[1] || 0;\n"
"    return result;\n"
"  }\n"
"\n"
"  if (isScenePort && (command === OTA_COMMANDS.set || command === OTA_COMMANDS.get_response)) {\n"
"    if (body.length < 16) throw new Error('Scene body too short');\n"
"    var configVersion = body[0];\n"
"    if (configVersion !== 1 && configVersion !== 2) throw new Error('Unsupported scene config version');\n"
"    var sceneFieldLength = port === 133 ? 4 : 3;\n"
"    var coordinateBytes = configVersion === 2 ? 3 : 4;\n"
"    var pointCount = body[11];\n"
"    if (body.length !== 13 + sceneFieldLength + pointCount * coordinateBytes) {\n"
"      throw new Error('Invalid scene body length');\n"
"    }\n"
"\n"
"    var found = sceneFor(port, { index: body[1] });\n"
"    var config = { points: [] };\n"
"    if (port === 131) {\n"
"      config.direction = body[13] ? 'rightToLeft' : 'leftToRight';\n"
"      config.publishClasses = classObject(body[14]);\n"
"    } else if (port === 132) {\n"
"      config.publishClasses = classObject(body[13]);\n"
"      config.valueType = ['max', 'min', 'average'][body[14]] || 'unknown';\n"
"    } else {\n"
"      config.classes = classObject(body[13]);\n"
"      config.thresholdObjectCount = body[14];\n"
"      config.triggerDelaySeconds = readU16(body, 15);\n"
"    }\n"
"\n"
"    for (var index = 0; index < pointCount; index++) {\n"
"      var offset = 13 + sceneFieldLength + index * coordinateBytes;\n"
"      var x;\n"
"      var y;\n"
"      if (configVersion === 2) {\n"
"        if (body[offset + 2] & 0xF0) throw new Error('Invalid packed coordinate');\n"
"        var packed = body[offset] + body[offset + 1] * 0x100 + body[offset + 2] * 0x10000;\n"
"        x = packed & 0x3FF;\n"
"        y = (packed >> 10) & 0x3FF;\n"
"        if (x > 1000 || y > 1000) throw new Error('Coordinate outside 0 through 1000');\n"
"      } else {\n"
"        x = readU16(body, offset);\n"
"        y = readU16(body, offset + 2);\n"
"        if (x === 0x8000 || y === 0x8000) throw new Error('Invalid Q15 coordinate');\n"
"        if (x & 0x8000) x -= 0x10000;\n"
"        if (y & 0x8000) y -= 0x10000;\n"
"        x = Math.round((x / 32767 + 1) * 500);\n"
"        y = Math.round((y / 32767 + 1) * 500);\n"
"      }\n"
"      config.points.push({ x: x, y: y });\n"
"    }\n"
"\n"
"    result.scene = {\n"
"      index: body[1],\n"
"      id: readU16(body, 2),\n"
"      name: found.scene.name,\n"
"      fingerprint: readU16(body, 4),\n"
"      mapFingerprint: readU16(body, 6)\n"
"    };\n"
"    result.page = body[8];\n"
"    result.pageCount = body[9];\n"
"    result.pointStart = body[10];\n"
"    result.totalPointCount = body[12];\n"
"    result.coordinateSystem = { origin: 'topLeft', minimum: 0, maximum: 1000 };\n"
"    result.config = config;\n"
"    return result;\n"
"  }\n"
"\n"
"  if (port === 130 && command === OTA_COMMANDS.get) {\n"
"    result.useCase = useCaseNames[body[0]] || body[0];\n"
"    return result;\n"
"  }\n"
"  if (port === 130 && (command === OTA_COMMANDS.set || command === OTA_COMMANDS.get_response)) {\n"
"    result.config = { useCase: useCaseNames[body[0]] || body[0], enabled: Boolean(body[1]) };\n"
"    if (body[0] !== OTA_USE_CASES.presence) result.config.intervalMinutes = body[2];\n"
"    return result;\n"
"  }\n"
"  if (port === 110 && command === OTA_COMMANDS.get) return result;\n"
"  if (port === 110 && (command === OTA_COMMANDS.set || command === OTA_COMMANDS.get_response)) {\n"
"    result.config = { fieldMask: body[0], dataRate: body[1], adrEnabled: Boolean(body[2]) };\n"
"    return result;\n"
"  }\n"
"  if (port === 100 && command === OTA_COMMANDS.set) {\n"
"    result.action = ({ 1: 'restartBridge', 2: 'resetAllData' })[body[0]] || body[0];\n"
"    return result;\n"
"  }\n"
"  if (port === 120 && command === OTA_COMMANDS.get) {\n"
"    result.infoType = ({ 1: 'cameraInfo', 2: 'bridgeInfo' })[body[0]] || body[0];\n"
"    result.page = body[1] || 0;\n"
"    return result;\n"
"  }\n"
"  if (port === 120 && command === OTA_COMMANDS.get_response) {\n"
"    result.infoType = ({ 1: 'cameraInfo', 2: 'bridgeInfo' })[body[0]] || body[0];\n"
"    if (body[1] === 0x81) return parseStructuredInformation(result, body);\n"
"    result.page = body[1];\n"
"    result.pageCount = body[2];\n"
"    result.text = String.fromCharCode.apply(null, body.slice(4, 4 + body[3]));\n"
"    return parseInformation(result, result.pageCount === 1);\n"
"  }\n"
"\n"
"  result.body = body;\n"
"  return result;\n"
"}\n"
"\n"
"/**\n"
" * Decode one frame with Decode(port, hex), or one/more frames with\n"
" * Decode({ port: Number, messages: String[] }). Multi-page information and\n"
" * scene responses are validated and merged.\n"
" */\n"
"function Decode(input, payload) {\n"
"  var port;\n"
"  var frames;\n"
"  if (payload != null) {\n"
"    port = Number(input);\n"
"    frames = [payload];\n"
"  } else if (input && input.port != null) {\n"
"    port = Number(input.port);\n"
"    frames = input.messages || input.frames || [input.message || input.payload || input.hex];\n"
"  } else {\n"
"    throw new Error('Decode expects {port,message}, {port,messages}, or (port,HEX)');\n"
"  }\n"
"\n"
"  var decoded = frames.map(function (frame) {\n"
"    return parseFrame(port, frame);\n"
"  });\n"
"  if (decoded.length > 1 && port === 120 && decoded.every(function (item) {\n"
"    return item.commandCode === OTA_COMMANDS.get_response;\n"
"  })) {\n"
"    decoded.sort(function (left, right) { return left.page - right.page; });\n"
"    var information = decoded[0];\n"
"    if (decoded.length !== information.pageCount) throw new Error('Incomplete information pages');\n"
"    var text = '';\n"
"    decoded.forEach(function (item, index) {\n"
"      if (\n"
"        item.transactionId !== information.transactionId ||\n"
"        item.commandCode !== information.commandCode ||\n"
"        item.infoType !== information.infoType ||\n"
"        item.page !== index ||\n"
"        item.pageCount !== information.pageCount\n"
"      ) {\n"
"        throw new Error('Mismatched information pages');\n"
"      }\n"
"      text += item.text;\n"
"    });\n"
"    information.text = text;\n"
"    delete information.page;\n"
"    delete information.pageCount;\n"
"    delete information.appVersionFragment;\n"
"    return parseInformation(information, true);\n"
"  }\n"
"  var isScenePort = port >= 131 && port <= 133;\n"
"  if (decoded.length > 1 && isScenePort && decoded.every(function (item) { return item.config; })) {\n"
"    decoded.sort(function (left, right) { return left.page - right.page; });\n"
"    var first = decoded[0];\n"
"    var points = [];\n"
"    if (decoded.length !== first.pageCount) throw new Error('Incomplete scene pages');\n"
"\n"
"    decoded.forEach(function (item, index) {\n"
"      var itemFields = JSON.stringify(Object.assign({}, item.config, { points: [] }));\n"
"      var firstFields = JSON.stringify(Object.assign({}, first.config, { points: [] }));\n"
"      if (\n"
"        item.transactionId !== first.transactionId ||\n"
"        item.commandCode !== first.commandCode ||\n"
"        item.scene.id !== first.scene.id ||\n"
"        item.scene.fingerprint !== first.scene.fingerprint ||\n"
"        item.scene.mapFingerprint !== first.scene.mapFingerprint ||\n"
"        item.page !== index ||\n"
"        item.pageCount !== first.pageCount ||\n"
"        item.pointStart !== points.length ||\n"
"        itemFields !== firstFields\n"
"      ) {\n"
"        throw new Error('Mismatched scene pages');\n"
"      }\n"
"      points = points.concat(item.config.points);\n"
"    });\n"
"\n"
"    if (points.length !== first.totalPointCount) throw new Error('Incomplete scene points');\n"
"    first.config.points = points;\n"
"    delete first.page;\n"
"    delete first.pageCount;\n"
"    delete first.pointStart;\n"
"    return first;\n"
"  }\n"
"  return decoded.length === 1 ? decoded[0] : decoded;\n"
"}\n"
"\n"
"\n";

static void Respond_Translator(ACAP_HTTP_Response response, int encoder) {
	cJSON* maps = OTA_Scene_Maps_JSON(ACAP_Get_Config("settings"));
	char* maps_text = maps ? cJSON_Print(maps) : NULL;
	cJSON_Delete(maps);
	if (!maps_text) {
		ACAP_HTTP_Respond_Error(response, 500, "Unable to read AOA scene map");
		return;
	}
	GString* javascript = g_string_sized_new(16384);
	g_string_append(javascript, "/** AI-B100 AOA OTA JavaScript ");
	g_string_append(javascript, encoder ? "Encoder" : "Decoder");
	g_string_append(javascript, " - generated for the current camera scene map. */\n");
	g_string_append_printf(javascript, "var OTA_SCENE_MAPS = %s;\n\n", maps_text);
	g_string_append(javascript, OTA_JS_COMMON);
	g_string_append(javascript, encoder ? OTA_ENCODER_JS : OTA_DECODER_JS);
	free(maps_text);
	char filename[96];
	snprintf(filename, sizeof(filename), "aib100-aoa-ota-%s-%s.js",
		encoder ? "encoder" : "decoder", ACAP_DEVICE_Date());
	ACAP_HTTP_Header_FILE(response, filename, "application/javascript", javascript->len);
	ACAP_HTTP_Respond_Data(response, javascript->len, javascript->str);
	g_string_free(javascript, TRUE);
}

void HTTP_Endpoint_OTA_Encoder(ACAP_HTTP_Response response, const ACAP_HTTP_Request request) {
	(void)request;
	Respond_Translator(response, 1);
}

void HTTP_Endpoint_OTA_Decoder(ACAP_HTTP_Response response, const ACAP_HTTP_Request request) {
	(void)request;
	Respond_Translator(response, 0);
}